# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-10-12 14:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0002_auto_20191010_1625'),
    ]

    operations = [
        migrations.AlterField(
            model_name='images',
            name='description',
            field=models.TextField(),
        ),
    ]
